version: "3.9"
services:
  kingscorp:
    image: kambang/kingscorp:notification
    container_name: kings-notification
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3003:3000
    volumes:
      - ./:/usr/src/app
    env_file: ./.env
    command: npm run start
